### ISSUE TITLE
3dtiles from cityGML

### ISSUE THREAD

**Issue by qdnguyen** [Oslandia/py3dtiles#1]
Hello,

Can i create a 3dtiles from cityGML with this tool? 

I have cityGMLs which contain 3D city models of paris and lyon in L93, i would like to create a 3dtiles of this models in wgs84.  Please tell me how can i do that?

Thanks a lot!

**Comment by Jeremy-Gaillard** [comment]
Hi,

With this tool, you can export WKB geometries to b3dm files. At Oslandia, we store the cityGML in a postgis database, so we can export easily to this format.

This tool does not create the tileset file however. For that, you can look at https://github.com/Oslandia/building-server (3d-tiles branch, it will soon be merged in the master). However, it only works in local coordinates for now, not in WGS84.
