### ISSUE TITLE
[ENH] Support for batch table hierarchy extension

### ISSUE THREAD

**Issue by EricBoix** [Oslandia/py3dtiles#27]
### The need
Among the available [3Dtiles extensions](https://github.com/AnalyticalGraphicsInc/3d-tiles/blob/master/extensions/README.md), the [batch table hierarchy extensions](https://github.com/AnalyticalGraphicsInc/3d-tiles/blob/master/extensions/3DTILES_batch_table_hierarchy/README.md) allows for "more complex metadata structures such as feature types or feature hierarchies".
The need for Py3DTiles is thus
 - to support this batch table hierarchy extension
 - to allow for the definition of other (possible user provided) extensions 

### Elements of reflection
 * As for the [current version](https://github.com/Oslandia/py3dtiles/tree/4e4d3677e0b856cc4ab283f8c9a329127fa584e1), the functionalities associated to a TileSet seem to be scattered (including the [writing of a TileSet](https://github.com/Oslandia/py3dtiles/blob/4e4d3677e0b856cc4ab283f8c9a329127fa584e1/py3dtiles/export.py#L111). This code structure makes it difficult to pinpoint the right location for introducing attaching some extension to a TileSet. Introducing a `TileSet` class would clarify the general code structure as well as the possible usage.
   For example we could write (something like):
   ```
    t = TileSet()
    for f in wkb_files:
        t.append_wkb(f)
    t.add_extension("3DTiles_batch_table_hierarchy")
    t.batch_table = ...
    t.write("tileset.json")
   ```   
 * The concrete mean for a 3D Tiles JSON object is to add an optional `extensions` dictionary property. They are as many data structures for `extensions` dictionary entries as they are documented extensions. PY3Dtiles could thus provide a mechanism to declare (on the fly i.e. after creation) that a given TileSet instance should bear some given specific extension. An extension itself could possibly be defined as class respecting an extension API (defined as an abstract class). A user could then write
   ```
    class my_time_extension(Py3dTiles.Extension):
       def name(self):
           return "time_extension"
        def to_json(self):
           ....

    TileSet.register_extension(my_time_extension)
    my_time_extension_content = <...some info...>
    t = TileSet()
    t.add_extension("time_extension", my_time_extension_content)
    t.write("tileset.json")
   ```
 *  PY3dTiles would provide the implementation of some standard extensions (e.g. batch table hierarchy) allowing a user to write (without having to register the "batch table hierarchy" standard extension) 
    ```
    t = TileSet()
    ...
    my_batch_table_content = <...some info...>
    t.add_extension("bach_table_hierarchy", my_batch_table_content)
    t.write("tileset.json")
   ```

**Comment by peppsac** [comment]
AFAICT this looks good - can't tell much more than that since I don't know much about the table hierarchy extenion.

**Comment by Jeremy-Gaillard** [comment]
[I started working on the batch table hierarchy extension a while ago](https://github.com/Jeremy-Gaillard/py3dtiles/blob/bt_hierarchy/py3dtiles/batch_table.py) (warning: it was made before the official 1.0 release).

I agree that we need a unified way of generating a tileset instead of creating the json by hand for each process. Probably something like this:
```python
ts = TileSet()
ts.add(tile, parentTile, sse, [some other relevant propery])
ts.write("tileset.json")
```

I don't think the user needs to explicitly specify which extension he uses (i.e. `ts.add_extension("3DTiles_batch_table_hierarchy"`). Extensions usualy add properties to tiles, we could therefore automatically deduce which extensions need to be declared when adding a tile to the tileset.

**Comment by EricBoix** [comment]
@Jeremy-Gaillard : 
 * yep, I did integrate (and start from) your work on the batch table hierarchy in [the version I'm working on](https://github.com/MEPP-team/py3dtiles/tree/bth) (at you can tell I went [cherry-picking on your work](https://github.com/MEPP-team/py3dtiles/commits/bth)).
* Actually, although this is obviously WIP and specially because I'm newbie to this 3DTiles business, I would really appreciate if you could throw in a review of what I did for now (aTdHvAaNnKcSe ? ;)
* After some thought I think you are totally right concerning the absence of need for having to a priori and explicitly specify which extension a given tileset will use. The a posteriori deduction scheme you propose now seems to me the way to go.

**Comment by Jeremy-Gaillard** [comment]
I think a tileset class should handle the building of the whole hierarchy, not only the tileset header. In other words, the node structure that is used in the various export scripts should be integrated in the tileset class.

Here is how I would design the class:
```python
class tileset
  def __init__(sse, transform)
  def addTile(tile, parentTile, sse, transform, refine, ...)
  def to_string() # writes json string
  def save_as(selt, filename, tileDirectory) # saves tileset and tiles
```

Edit: I probably forgot a few things, such as the possibility to add [external tilesets](https://github.com/AnalyticalGraphicsInc/3d-tiles/tree/master/specification#external-tilesets). We may also want a read function to analyse an existing tileset.

**Comment by jailln** [comment]
@Jeremy-Gaillard : 
- With your proposition, when do you compute the hierarchy of tiles from the geometries? 
- sse, transform, refine, etc. are attributes of the tile so I don't think they need to be passed as arguments to addTile because they should be contained in tile.

**Comment by Jeremy-Gaillard** [comment]
- The way a hierarchy is computed, how the objects are grouped into tiles, how level of details are generated, highly depends on the application. The tileset class is not meant to handle this kind of logic, but only to facilitate the formating of the json file. The computing of the hierarchy of tiles is either dones by scripts provided by py3dtiles (e.g; export_tileset) or by the user that imports the lib.
- That's a good point, though I'm a bit reluctant to add these attributes to the tile class since they are not in the tile files. Not sure what is the best solution honestly

**Comment by jailln** [comment]
* I agree with you that these functions should not necessarily be held by the tileset. However I think that py3dtiles should provide some based on usual indexing methods and which could be configured (e.g. createQuadtreeTileset(config_args)) These functions could for instance be static functions of py3dtiles so they can be used by external tools.

* [They are attributes of the tile](https://github.com/AnalyticalGraphicsInc/3d-tiles/blob/master/specification/schema/tile.schema.json) so I think that they should be held by a Tile object. (see next point)

* In the current implementation of py3DTiles it seems that the Tile object is an interface for the b3dm and pnts classes. [In the specification](https://github.com/AnalyticalGraphicsInc/3d-tiles/blob/master/specification/schema/tile.schema.json) though, a tile is a node of the tileset and points to the content of the tile (e.g. b3dm or pnts).  So maybe we should rename the Tile object of py3dtiles to e.g. TileContent and create a Tile object which implements the actual Tile class of the spec.

**Comment by EricBoix** [comment]
I would be tempted to follow @jailln's proposition (within this implementation) for **renaming  the Tile object to become TileContent**. Indeed if we look at the definition of e.g. a [b3dm](https://github.com/Oslandia/py3dtiles/blob/master/py3dtiles/b3dm.py#L10):
 - it inherits from ["Tile"](https://github.com/Oslandia/py3dtiles/blob/master/py3dtiles/tile.py#L8)
 - but it has a header and a body (notions that don't exist [in 3DTiles's Tile specification](https://github.com/AnalyticalGraphicsInc/3d-tiles/blob/master/specification/schema/tile.schema.json)
 - the [B3dmHeader attributes](https://github.com/Oslandia/py3dtiles/blob/master/py3dtiles/b3dm.py#L77) are the one of a [Batched3DModel](https://github.com/AnalyticalGraphicsInc/3d-tiles/blob/master/specification/TileFormats/Batched3DModel/README.md#header)
 - and Batched 3D model is in fact a [Tile content](https://github.com/AnalyticalGraphicsInc/3d-tiles/tree/master/specification#tile-format-specifications) that follows the associated [Tile content schema](https://github.com/AnalyticalGraphicsInc/3d-tiles/blob/master/specification/schema/tile.schema.json#L36)

**Comment by Jeremy-Gaillard** [comment]
I agree, your proposition is what fits best with the specification.

Concerning @jailln first point, I guess we could expose some of our indexing functions, though I don't think that's there's a lot of value in them at the moment (in export.py at least). Maybe we could build something more ambitious and generic, but I dont know if it falls within the scope of the project (ping @peppsac).

**Comment by Mitko88** [comment]
@Jeremy-Gaillard 

Are you still working on this issue? Is there any progress?

**Comment by EricBoix** [comment]
@Mitko88
The [VCity lab project](https://projet.liris.cnrs.fr/vcity/wiki/doku.php), to which I belong (and where @Jeremy-Gaillard conduced his Phd), is currently working on the [Batch Table Hierarchy support](https://github.com/MEPP-team/py3dtiles/tree/Tiler/py3dtiles). We didn't submit a PR to Oslandia yet (because we are testing those new features on a Tiling algorithm) but we should be doing so in the next month.
Meanwhile feel free to test/comment on [what we've done on our branch](https://github.com/MEPP-team/py3dtiles/tree/Tiler/py3dtiles) and/or discuss with us on such topics.

**Comment by Mitko88** [comment]
That is great! Keep up with the good work!
I tested some stuff with your library and it works nicely.

**Comment by delhomer** [comment]
Moved to https://gitlab.com/Oslandia/py3dtiles/-/issues/27
