### ISSUE TITLE
Debian 8.11 seems too old to install Numba Py3Dtiles' dependency 

### ISSUE THREAD

**Issue by EricBoix** [Oslandia/py3dtiles#28]
Platform:
  - OS: Debian 8.11
  - Python: 3.4.2

When launching the `pip install -e .` command of [py3dtiles' install](https://github.com/Oslandia/py3dtiles/blob/master/README.rst#install), pip eventually pulls various python packages sub-dependencies that fail building:
  1. Numba (building wheel fail)
      Numba seems to depend on numpy but doesn't pull that dependency. This can be solved with a manual call to `pip install numpy`. Then `pip install numba` succeeds.
  2. `llvmlite` (building wheel fail)
      * In order to build, `llvmlite` requires the `llvm-config` command line utility (that seems to come packaged with llvm)
      * `apt-get install llvm` will install `llvm-config` version 3.5.0 (that is the version of llvm itself).
      *  But the `pip install lvmlite` command will terminate with the message
         ```
         RuntimeError: Building llvmlite requires LLVM 6.0.x.
         ```
Note that this seems to be a [known issue of Numba on Debian 8](https://stackoverflow.com/questions/34495356/python-numba-llvmlite-on-debian-8-i-cant-build-llvmlite)
 
I guess the conclusion is that Debian version 8.11 default package numbers are too old to support some straightforward install of Py3DTiles (because of its Numba sub-dependency).

Suggestion: maybe we should create some "Platforms where Py3DTiles install was reported to fail" chapter/entry in the Py3DTiles install notes that mentions Debian8 ? And then simply close this issue...

**Comment by delhomer** [comment]
https://gitlab.com/Oslandia/py3dtiles/-/issues/28
