### ISSUE TITLE
gltfUpAxis not part of 3DTiles specification

### ISSUE THREAD

**Issue by fhoubie** [Oslandia/py3dtiles#30]
The conversion of a LAS file to 3DTiles generates a gltfUpAxis property in the tileset.json file. This property is not part of the 3DTiles specification.

**Comment by peppsac** [comment]
Indeed this part has been removed before the 1.0 version release of the spec.

It should be moved to the `asset.extras` property (see https://github.com/AnalyticalGraphicsInc/3d-tiles/blob/master/specification/schema/asset.schema.json#L19).

Another change would be to rename `content.url` to `content.uri`  (https://github.com/AnalyticalGraphicsInc/3d-tiles/blob/master/specification/schema/tile.content.schema.json)

**Comment by Jeremy-Gaillard** [comment]
If I understand the [spec](https://github.com/AnalyticalGraphicsInc/3d-tiles/tree/master/specification#gltf) correctly, the gltfUpAxis property has completly disapeared and glTf files are now always considered y-up.  We need to remove the property and either:
- garantee that all imported meshes are y-up
- add a z-up to y-up transformation to each glTF object

In any case, this does not affect pnts tiles, and glTfUpAxis can safely be removed from the LAS to 3D Tiles conversion utility.
