### ISSUE TITLE
Two (minor) remarks about the install documentation

### ISSUE THREAD

**Issue by EricBoix** [Oslandia/py3dtiles#34]
### Is requirements.txt still used ?
The from sources [installation commands](https://github.com/Oslandia/py3dtiles/blob/master/docs/install.rst#from-sources) currently require to launch a `pip install -e .`. 
I don't know why (since I don't much about python install/distutils/setup thingies) but I can succeed with my py3dtiles installation without running that command.

Actually I can remove the [`requirements.txt`](https://github.com/Oslandia/py3dtiles/blob/master/requirements.txt) file at all and the installation still succeeds. 

Hence my question: are they some use cases or contexts where `requirements.txt` and the  `pip install -e .` are required for things to run smoothly ?

I'm asking this because when you add a new module requirement to py3dtiles, you currently apparently seem to need to update both `requirements.txt` and the [requirements section of setup.py](https://github.com/Oslandia/py3dtiles/blob/master/setup.py#L8) (which doesn't look that [DRY](https://en.wikipedia.org/wiki/Don't_repeat_yourself)?).  

### Do we need to hard wire the path to python3 in command `virtualenv -p /usr/bin/python3 venv` ?
The [installation commands](https://github.com/Oslandia/py3dtiles/blob/master/docs/install.rst#from-sources) also mention to `virtualenv -p /usr/bin/python3 venv`. Yet on OSX the python3 interpreter is not located by default in `/usr/bin` (both native and homebrew versions). 
I thus had to run `virtualenv -p python3 venv` which looks more platform independent (it suffice to change your PATH to point to a specific version prior to launching the command).

**Comment by peppsac** [comment]
Regarding the first question: AFAIU, `requirements.txt` should contain the output of `pip freeze` = all the resolved dependencies with their specific version. On the other hand, `setup.py` contains unversionned dependencies.
So there are 2 ways of installing py3dtiles:
- `pip install [-e] PY3DTILES_FOLDER`
- `pip install -r  PY3DTILES_FOLDER/requirements.txt`

Regarding the 2nd question: yes, `virtualenv -p python3 venv` would be better

**Comment by delhomer** [comment]
https://gitlab.com/Oslandia/py3dtiles/-/issues/34
