### ISSUE TITLE
task/las_reader.py  Runtime error

### ISSUE THREAD

**Issue by jiawenquan** [Oslandia/py3dtiles#35]
D:\ProgramData\Anaconda3\envs\newpy3dtiles\python.exe E:/GitProject/py3dtiles/py3dtiles/points/task/las_reader.py
Traceback (most recent call last):
  File "E:/GitProject/py3dtiles/py3dtiles/points/task/las_reader.py", line 8, in <module>
    import liblas
  File "D:\ProgramData\Anaconda3\envs\newpy3dtiles\lib\site-packages\liblas\__init__.py", line 2, in <module>
    from .core import get_version
  File "D:\ProgramData\Anaconda3\envs\newpy3dtiles\lib\site-packages\liblas\core.py", line 139, in <module>
    las = ctypes.CDLL(lib_name)
  File "D:\ProgramData\Anaconda3\envs\newpy3dtiles\lib\ctypes\__init__.py", line 348, in __init__
    self._handle = _dlopen(self._name, mode)
OSError: [WinError 126] 找不到指定的模块。

 I use `python3.6` 

 (newpy3dtiles) C:\Users\Administrator>pip list
Package                  Version
------------------------ ---------
alabaster                0.7.12
atomicwrites             1.2.1
attrs                    18.2.0
Babel                    2.6.0
certifi                  2018.8.24
chardet                  3.0.4
colorama                 0.3.9
coverage                 4.5.1
Cython                   0.28.5
decorator                4.1.2
docutils                 0.14
idna                     2.7
imagesize                1.1.0
ipython                  6.1.0
ipython-genutils         0.2.0
jedi                     0.10.2
Jinja2                   2.10
laspy                    1.5.1
libLAS                   1.8.1
line-profiler            2.0
llvmlite                 0.20.0
lz4                      0.10.1
MarkupSafe               1.0
more-itertools           4.3.0
numba                    0.35.0
numpy                    1.13.1
packaging                18.0
path.py                  10.3.1
pickleshare              0.7.4
pip                      18.1
pluggy                   0.7.1
prompt-toolkit           1.0.15
psutil                   5.4.7
psycopg2-binary          2.7.5
py                       1.6.0
py-cpuinfo               4.0.0
Pygments                 2.2.0
pyparsing                2.2.2
pyproj                   1.9.5.1
pytest                   3.8.2
pytest-benchmark         3.1.1
pytest-cov               2.6.0
pytz                     2018.5
pyzmq                    17.1.2
requests                 2.19.1
setuptools               36.4.0
simplegeneric            0.8.1
six                      1.10.0
snowballstemmer          1.2.1
Sphinx                   1.8.1
sphinx-rtd-theme         0.4.2
sphinxcontrib-websupport 1.1.0
traitlets                4.3.2
triangle                 20170429
urllib3                  1.23
wcwidth                  0.1.7
wheel                    0.29.0
wincertstore             0.2

I don't know where the problem is

**Comment by jiawenquan** [comment]
I solved the problem

`pip install liblas`  The version is **wrong**!!

so download the whl file，To install http://www.lfd.uci.edu/~gohlke/pythonlibs/#liblas

`python install libLAS-1.8.1-cp36-cp36m-win_amd64`

Everything is all right  ：)

**Comment by EricBoix** [comment]
On my OSX 10.13.6., Python 3.6.5, the libLAS version that gets pulled by the Py3DTiles install is version 1.8.1 (for which tests and demos are OK).
When you say that the "version is wrong", do you mean that 
 1. you previously had another installed version of libLAS (say 1.7.X or 1.8.0) for which it doesn't work ?
 2. the version pulled by default is wrong ?

If this were to be case 2, are you suggesting that the [setup.py](https://github.com/Oslandia/py3dtiles/blob/master/setup.py#L14) should require that `liblas>=1.8.0` ?

**Comment by jiawenquan** [comment]
@EricBoix 
On my Windows 10 .， Python 3.6.2

2. the version pulled by default is wrong

I think I probably pulled down the 32-bit version
But 64-bit version works
