### ISSUE TITLE
I't trying to get a python application running on Windows and I get an ZMQError: Protocol not supported which is because ipc is not supported on windows. 

### ISSUE THREAD

**Issue by jiawenquan** [Oslandia/py3dtiles#37]
```
def zmq_process(activity_graph, projection, node_store, octree_metadata, folder, write_rgb, verbosity):
    context = zmq.Context()

    # Socket to receive messages on
    skt = context.socket(zmq.DEALER)
    skt.connect('ipc:///tmp/py3dtiles1')
```

So I hope  `ipc `to be changed to `tcp`

**Comment by chenaza** [comment]
Hi,have you resovled this problem on windows?

**Comment by autra** [comment]
@chenaza if I'm not mistaken it's https://github.com/Oslandia/py3dtiles/pull/39. But this is waiting for @jiawenquan to address a couple of comment.

As it is nearly 1 year old, feel free to take over this PR.

**Comment by chenaza** [comment]
@autra Thank you for your answer！

**Comment by radi2015** [comment]
@chenaza Hi Are you chinese?

**Comment by delhomer** [comment]
https://gitlab.com/Oslandia/py3dtiles/-/issues/37
