### ISSUE TITLE
About: Cannot display PNTS after converting LAS with Input SRS WGS84 Projection

### ISSUE THREAD

**Issue by HuyQuoc** [Oslandia/py3dtiles#45]
I'm trying to convert LAS to 3DTiles using Py3DTiles. 

Hi, I'm succeed in installing Py3DTiles but I cannot display 3DTiles after installed. 

I used LAS Viewer to compare output PNTS file with your tested PNTS and found problem relate to difference CRS. Your tested PNTS using projected CRS and my output using lonlat CRS. I dont know how to convert to the right CRS of Py3DTiles. 

Please help me to fix this. 
Thank you.

**Comment by peppsac** [comment]
Could you answer these questions to help us help you:
- what command line did you use to convert your las file?
- what CRS does you las file uses?
- what 3dtiles viewer do you use?

Thanks!

**Comment by HuyQuoc** [comment]
> Could you answer these questions to help us help you:
> 
> * what command line did you use to convert your las file?
> * what CRS does you las file uses?
> * what 3dtiles viewer do you use?
> 
> Thanks!

Hi Peppsac,

I used follow:  
- Command Line: py3dtiles convert {path}/pointcloud.las --out {path}/pointcloud --srs_in 32648 --srs_out 4326 
- CRS: EPSG 32648 
- 3DTiles Viewer: CesiumJS: 
`var viewer = new Cesium.Viewer('cesiumContainer', {
    shadows : false
});
viewer.scene.globe.depthTestAgainstTerrain = true;
viewer.infoBox.frame.removeAttribute('sandbox');
var tileset = viewer.scene.primitives.add(new Cesium.Cesium3DTileset({
  url: '3D/LAS/4326_PointCloud/tileset.json'
}));
tileset.readyPromise.then(function(tileset) {
  viewer.zoomTo(tileset, new Cesium.HeadingPitchRange(0, -2.0, Math.max(100.0 - tileset.boundingSphere.radius, 0.0)));
}).otherwise(function(error) {
  console.log(error);
});`

Another Note: I tried to convert LAS to 3DTiles in FME DATA TRANSLATOR with same parameters of CRS: 
Input CRS: EPSG 32648 
Output CRS: EPSG 4326 
After that I can display 3DTiles in Cesium without error but it's really heavy because FME only export data to one file *.pnts. 

Thanks & Regards.

**Comment by peppsac** [comment]
To display the 3dtiles file in Cesium you should use the EPSG:4978 output srs (so `--srs_out 4978` instead of `--srs_out 4326`).

**Comment by HuyQuoc** [comment]
> EPSG:4978

OMG. I can display my data now. Big thanks to you peppsac. 

I have another question: 
- How can i get pointcloud propterties for styling (or How can I have Batched Point Cloud after converting from LAS) ? I checked in PNTS viewer but cannot see properties of point cloud in this example: https://cesiumjs.org/Cesium/Build/Apps/Sandcastle/?src=3D%20Tiles%20Point%20Cloud%20Styling.html

- I also want to convert CityGML to 3DTiles. At the moment, I'm using CityTiler (supported with py3DTiles) but when I convert directly CityGML file (*.gml) to py3DTiles that it's required a 3D CityDB ? What's supported CityGML version of py3DTiles ? Do u have any experience on it ? 

Regards.

**Comment by Jeremy-Gaillard** [comment]
> I also want to convert CityGML to 3DTiles. At the moment, I'm using CityTiler (supported with py3DTiles) but when I convert directly CityGML file (*.gml) to py3DTiles that it's required a 3D CityDB ? What's supported CityGML version of py3DTiles ? Do u have any experience on it ?

CityTiler relies on 3D City DB to read CityGML files. You will need to download 3D City DB (version 3.3.2) and have a running postGIS database. CityTiler supports CityGMLv2. However, I would like to point out that CityTiler is still an early prototype and, depending on how the CityGML is structured, it may not work properly.

**Comment by HuyQuoc** [comment]
> > I also want to convert CityGML to 3DTiles. At the moment, I'm using CityTiler (supported with py3DTiles) but when I convert directly CityGML file (*.gml) to py3DTiles that it's required a 3D CityDB ? What's supported CityGML version of py3DTiles ? Do u have any experience on it ?
> 
> CityTiler relies on 3D City DB to read CityGML files. You will need to download 3D City DB (version 3.3.2) and have a running postGIS database. CityTiler supports CityGMLv2. However, I would like to point out that CityTiler is still an early prototype and, depending on how the CityGML is structured, it may not work properly.

Py3DTiles also can export data from 3DCityDB to 3DTiles, right ? I tried to install 3DCityDB in Terminal Command Line (myOS has no GUI) but cannot success ? Do u have any suggest to display CityGML on Web using Cesium ?

**Comment by peppsac** [comment]
@HuyQuoc, if you don't mind I'd suggest to open a new issue to discuss the CityGML aspect.

**Comment by HuyQuoc** [comment]
> @HuyQuoc, if you don't mind I'd suggest to open a new issue to discuss the CityGML aspect.

Yes, It's no problem @peppsac . I'm very glad when have ur support.
