### ISSUE TITLE
Error after converting big las file (over 2GB)!

### ISSUE THREAD

**Issue by HuyQuoc** [Oslandia/py3dtiles#46]
Hi, 

I got this error when i tried to convert a big LAS file (over 2GB). With small file (less than 1GB), everything is fine. Can u explain for me about this and how can i fix it or is this affected to converted 3dtiles ?

My Computer has 4 CPU 64bit processors, RAM 16GB with No-GPU. 

> /DockerShared/py3dtiles/venv/lib/python3.5/site-packages/py3dtiles-1.1.0-py3.5.egg/py3dtiles/convert.py:336: RuntimeWarning: invalid value encountered in subtract
> x_axis = br - bl
> /DockerShared/py3dtiles/venv/lib/python3.5/site-packages/py3dtiles-1.1.0-py3.5.egg/py3dtiles/convert.py:338: RuntimeWarning: invalid value encountered in subtract
> bl = bl - avg_min
> /DockerShared/py3dtiles/venv/lib/python3.5/site-packages/py3dtiles-1.1.0-py3.5.egg/py3dtiles/convert.py:339: RuntimeWarning: invalid value encountered in subtract
> tr = tr - avg_min
> /DockerShared/py3dtiles/venv/lib/python3.5/site-packages/py3dtiles-1.1.0-py3.5.egg/py3dtiles/convert.py:83: RuntimeWarning: invalid value encountered in true_divide
> v0 = z1 / np.linalg.norm(z1)
> /DockerShared/py3dtiles/venv/lib/python3.5/site-packages/py3dtiles-1.1.0-py3.5.egg/py3dtiles/convert.py:354: RuntimeWarning: invalid value encountered in minimum
> np.minimum(bl, tr),
> /DockerShared/py3dtiles/venv/lib/python3.5/site-packages/py3dtiles-1.1.0-py3.5.egg/py3dtiles/convert.py:355: RuntimeWarning: invalid value encountered in maximum
> np.maximum(bl, tr)
> 0.0 % in 0 sec [est. time left: 14151 sec]/DockerShared/py3dtiles/venv/lib/python3.5/site-packages/py3dtiles-1.1.0-py3.5.egg/py3dtiles/points/node.py:132: RuntimeWarning: invalid value encountered in greater_equal
> indices = xyz_to_child_index(pending_xyz_arr, self.aabb_center)
> 1.19 % in 2 sec [est. time left: 169 sec]/DockerShared/py3dtiles/venv/lib/python3.5/site-packages/py3dtiles-1.1.0-py3.5.egg/py3dtiles/points/node.py:132: RuntimeWarning: invalid value encountered in greater_equal
> indices = xyz_to_child_index(pending_xyz_arr, self.aabb_center)
> 7.85 % in 18 sec [est. time left: 211 sec]/DockerShared/py3dtiles/venv/lib/python3.5/site-packages/py3dtiles-1.1.0-py3.5.egg/py3dtiles/points/task/las_reader.py:118: RuntimeWarning: invalid value encountered in add
> x = (x + offset_scale[0][0]) * offset_scale[1][0]
> /DockerShared/py3dtiles/venv/lib/python3.5/site-packages/py3dtiles-1.1.0-py3.5.egg/py3dtiles/points/task/las_reader.py:119: RuntimeWarning: invalid value encountered in add
> y = (y + offset_scale[0][1]) * offset_scale[1][1]
> 17.78 % in 41 sec [est. time left: 192 sec]/DockerShared/py3dtiles/venv/lib/python3.5/site-packages/py3dtiles-1.1.0-py3.5.egg/py3dtiles/points/task/las_reader.py:118: RuntimeWarning: invalid value encountered in add
> x = (x + offset_scale[0][0]) * offset_scale[1][0]
> /DockerShared/py3dtiles/venv/lib/python3.5/site-packages/py3dtiles-1.1.0-py3.5.egg/py3dtiles/points/task/las_reader.py:119: RuntimeWarning: invalid value encountered in add
> y = (y + offset_scale[0][1]) * offset_scale[1][1]

Thanks.
Regards.

**Comment by delhomer** [comment]
Moved to https://gitlab.com/Oslandia/py3dtiles/-/issues/46
