### ISSUE TITLE
Batch table support

### ISSUE THREAD

**Issue by bwyss** [Oslandia/py3dtiles#48]
I would like to style per point metadata in 3d tiles using the cesiumJS [styling specification](https://github.com/AnalyticalGraphicsInc/3d-tiles/tree/master/specification/Styling).

To do so (I believe) I need batch table support. Are there any plans for implementing batch table support?

**Comment by delhomer** [comment]
Moved to https://gitlab.com/Oslandia/py3dtiles/-/issues/48
