### ISSUE TITLE
Incorrect winding order on some polygons

### ISSUE THREAD

**Issue by RubioV** [Oslandia/py3dtiles#49]
Polygons are triangulated in wkb_utils.py, after which the winding order of each triangle is checked to make sure it is the same as the winding order of the source polygon. However, this check is only done on the first vertices of the polygon, and if the start of the polygon happens to be convex, an incorrect winding order is assumed. This will lead to an inverted winding order on the resulting triangles. 

See below for an example. The start of the roof polygon is convex. Because of this, py3dtiles inverts the winding order, leading to an inversion of the normals and the polygon not being rendered.

![image](https://user-images.githubusercontent.com/107693/54686289-37909a80-4b19-11e9-8020-443d6911f81e.png)

To fix this issue, the winding order should be calculated for the entire polygon, rather than the first few vertices, I will submit a pull request to fix this.

**Comment by RubioV** [comment]
This might also be fixed by https://github.com/Oslandia/py3dtiles/pull/18, which seems to provide a simpler solution. However, I haven't tested that solution.

**Comment by Jeremy-Gaillard** [comment]
Hi,

Thanks for the PR. I had indeed tried to fix the problem a little while back, but (if I remember correctly), it reduced quite significantly the performance. I will try to look more into it once I have a bit more time on my hands, and merge one of the two PRs.

**Comment by autra** [comment]
@Jeremy-Gaillard oh I remember that. Didn't we fix it in https://github.com/Oslandia/py3dtiles/commits/3d-tiles-improved ?

**Comment by Jeremy-Gaillard** [comment]
@autra unfortunately no, it's a problem that is induced by #18. IIRC it's the use of `np.linalg.norm` that is very costly.

**Comment by delhomer** [comment]
Moved to https://gitlab.com/Oslandia/py3dtiles/-/issues/49
