### ISSUE TITLE
building 'triangle.core' extension error install

### ISSUE THREAD

**Issue by paulopires16** [Oslandia/py3dtiles#51]
running build_ext
building 'triangle.core' extension
error: [Error 2] The system cannot find the file specified

----------------------------------------
Command "c:\python27\python.exe -u -c "import setuptools, tokenize;__file__='c:\\windows\\temp\\pip-install-zso2cu\\triangle\\setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" install --record c:\windows\temp\pip-record-gu3guo\install-record.txt --single-version-externally-managed --compile" failed with error code 1 in c:\windows\temp\pip-install-zso2cu\triangle\

**Comment by Jeremy-Gaillard** [comment]
It seems you are using python2. py3dtiles uses python3. This may be the cause of your problem.

**Comment by delhomer** [comment]
Moved to https://gitlab.com/Oslandia/py3dtiles/-/issues/51
