### ISSUE TITLE
OSError: liblas_c.so.3: cannot open shared object file: No such file or directory

### ISSUE THREAD

**Issue by xhepburn** [Oslandia/py3dtiles#55]
i install the package in centos ，but raise this problem.i can't find  liblas_c.so.3 and where  should i put it ?thanks for solve this problen

**Comment by autra** [comment]
@xhepburn I need more info:

- what is your version of centos
- can you give me the full logs of your session? Including : which command did you use to install py3dtiles and the full output, and which command failed (if different from the installation command) and the full output please.

Thanks!

**Comment by xhepburn** [comment]
> @xhepburn我需要更多信息：
> 
> * 你的centos版本是什么？
> * 你能告诉我你会议的完整日志吗？包括：您使用哪个命令来安装py3dtiles和完整输出，以及哪个命令失败（如果与安装命令不同）请完整输出。
> 
> 谢谢！

my centos version is 'CentOS Linux release 7.6.1810 (Core)'  and i download py3dtiles and use python setup.py to setup this package,i want to convert my lasfile to 3dtiles ,my commda is 'py3dtiles convert Test.las --out /root/tiles', my english is not very good ,

**Comment by autra** [comment]
> my english is not very good ,

No problem, it'll always be better than my chinese ;-)

Did you install [liblas](https://liblas.org) beforehand?

**Comment by delhomer** [comment]
Moved to https://gitlab.com/Oslandia/py3dtiles/-/issues/55
