### ISSUE TITLE
Make a logo :-)

### ISSUE THREAD

**Issue by autra** [Oslandia/py3dtiles#61]
Let's have a logo for py3dtiles.

Some keywords:

3d, 3dtiles, pointclouds, buildings, streaming, conversion, multiprocessing...

**Comment by autra** [comment]
@sylvainbeo do you want to do it? :-)

**Comment by autra** [comment]
some idea for color combos: https://www.colorcombos.com/color-schemes/8347/ColorCombo8347.html

https://www.colorcombos.com/color-schemes/16/ColorCombo16.html

**Comment by sylvainbeo** [comment]
@autra Sure.
