### ISSUE TITLE
Release v2

### ISSUE THREAD

**Issue by autra** [Oslandia/py3dtiles#67]
I think cac2193 alone justify this release. It's also a good reason to release a major version :-)

TODO:
- add metadata to setup.py for pypi website
   - link to doc
- make a release note and a migration note
- check the doc

@delhomer wdyt?

**Comment by autra** [comment]
Also before releasing a major version, I think we should discuss about the current cli and api, and see if we are happy about it. If we are doing breaking changes, it's better to do it right.

**Comment by delhomer** [comment]
Ok for breaking stuffs *before* any major release... ;)

I see in the [dashboard](https://github.com/Oslandia/py3dtiles/releases) that there is only a few releases. Maybe we should be fine with a `1.1` version?

**Comment by autra** [comment]
> Maybe we should be fine with a `1.1` version?

I'd like to respect semver (any breaking change goes into a new major). I like when lib I use respect it, so I want to do so as well here :-) I think it gives valuable information to users.

**Comment by delhomer** [comment]
> I'd like to respect semver (any breaking change goes into a new major). I like when lib I use respect it, so I want to do so as well here :-) I think it gives valuable information to users.

Fine for me.
