### ISSUE TITLE
Wrong transformation or rotation in b3dm export

### ISSUE THREAD

**Issue by mholthausen** [Oslandia/py3dtiles#78]
There seems to be an error in the exporting of a b3dm in the transformation or rotation of the gltf object and the tileset boundingVolume box.
I have exported the Polyhedralsurface (in `EPSG:4978`) which is based on a DalunayTriangles TINZ of theses XYZ points (in `EPSG:31468`):

```text
4577799, 5809394, 112
4566546, 5809394, 112
4623589, 5809394, 112
4623589, 5837277, 112
4566546, 5837277, 112
4577799, 5837277, 112
```

The area should be a "flat plane" at the height of 112 meters. But the resulting tileset has a rotation in the boundingVolume box and a boundingVolume extent that does not include all parts of the gltf object.

```javscript
let boundingSphere = tileset.boundingSphere;
let cartographic = Cartographic.fromCartesian(boundingSphere.center);

let surface = Cartesian3.fromRadians(cartographic.longitude, cartographic.latitude, 0.0);
let matrix = Transforms.eastNorthUpToFixedFrame(surface);
tileset.root.transform = matrix;
```

Executing the above code on the tileset in the Cesium viewer fixes the rotation of the boundingVolume box, but the gltf object is tilted. When I view the gltf in a [gltf Viewer](https://gltf-viewer.donmccurdy.com/) I see also a tilted plane (note the attached scrrenshots).

![tilted_boundingVolume](https://user-images.githubusercontent.com/43119593/75539817-29324a80-5a1b-11ea-827c-d362741b3cfb.png)

![tilted_plane](https://user-images.githubusercontent.com/43119593/75539790-1e77b580-5a1b-11ea-9d19-32990d3807e6.png)

![gltf_viewer](https://user-images.githubusercontent.com/43119593/75540285-03f20c00-5a1c-11ea-9144-753c7c45f538.png)

* the calculation of the boundingVolume must generate incorrect values that lead to a tilting of the box and an incorrect extent,
* the glTF object also receives a tilt that does not correspond to the geometry of the initial values

**Comment by autra** [comment]
Hi @mholthausen!

> I have exported the Polyhedralsurface (in `EPSG:4978`)

what is exactly the code / command you used to export this surface? 

Can you attach a screenshot of the plane before changing the tileset matrix in cesium? 

Thanks

**Comment by delhomer** [comment]
Moved to https://gitlab.com/Oslandia/py3dtiles/-/issues/78
