### ISSUE TITLE
When Point cloud zoom ou ,it disappeared

### ISSUE THREAD

**Issue by whuxxie** [Oslandia/py3dtiles#79]
i try to convert txt format point cloud(e.g format: x y z r g b) to 3D Tiles (.pnts),it successed,but in Cesium,when I want to zoom out, it disappered.
and next problem  is ,what is the format of xyz?when i convert ,the position is wrong ,totally strange.
i use WGS84Plane coordinate system，like
2552604.4 187598.9 0.0 6 18 24
2552604.4 187599.9 0.0 56 25 188
2552604.4 187600.9 0.0 232 77 222
2552604.4 187601.9 0.0 78 60 161
2552604.4 187602.9 0.0 180 215 55
2552604.4 187603.9 0.0 141 171 189
2552604.4 187604.9 0.0 142 216 27
this position is in China

**Comment by autra** [comment]
Hi @whuxxie, what command did you use to convert your pointcloud?

**Comment by whuxxie** [comment]
> Hi @whuxxie, what command did you use to convert your pointcloud?

i use py3dtiles convert point.xyz --out /tmp/destination

**Comment by autra** [comment]
hi @whuxxie, what CRS your point.xyz is in? If you don't know, you can give the first 10 or so points. 

Short story, you need to use `--srs_in <your_crs>` and `--srs_out 4978`

**Comment by delhomer** [comment]
Moved to https://gitlab.com/Oslandia/py3dtiles/-/issues/79
