### ISSUE TITLE
Add B3DM Feature Table

### ISSUE THREAD

**Issue by FreakTheMighty** [Oslandia/py3dtiles#80]
The b3dm feature table is pretty simple compared to the point cloud feature table - in fact it almost seems unnecessary.  Nonetheless, to make the generated b3dm + batch table to spec, it'd be nice to include the feature table.

There is one related closed ticket here without resolution. #75 

I'm happy to contribute a fix for this - I'm wondering though if we need to tackle a bit of refactoring here by creating some sort of base FeatureTable that is shared between point clouds and b3dm?

**Comment by delhomer** [comment]
Moved to https://gitlab.com/Oslandia/py3dtiles/-/issues/80
